### PR TITLE
fix: Authentication bug on PRs from forks

### LINKED ISSUE #127: Resolve issue authenticating PRs from forks
**What is the problem we're trying to solve?**

In running tests on [this PR](https://github.com/MobilityData/mobility-database-catalogs/pull/126) after I forked the repo, this error kept recurring : 

`Error: google-github-actions/auth failed with: the GitHub Action workflow must specify exactly one of "workload_identity_provider" or "credentials_json"! If you are specifying input values via GitHub secrets, ensure the secret is being injected into the environment. By default, secrets are not passed to workflows triggered from forks, including Dependabot.`

[It looks like this is because secrets are not injected on PRs from forks](https://github.com/google-github-actions/auth/issues/52#issuecomment-975622085).

This needs to be fixed in order for us to accept contributions.

**How do we know when this is done?**

PRs from forked repos can be accepted without the error.

### PR DESCRIPTION
**Pull request by maximearmstrong**
**Summary:**

Fixes #127: Resolve issue authenticating PRs from forks

The initial pipeline built to store the latest datasets on approval won't work when merging contribution from forks because the GCP secrets are stored in our repository. This secret cannot be shared at all, so the `store_latest_dataset_on_approval.yml` workflow is deleted as it is causing the authenticating issue. 

Our daily cronjob will keep updating the latest datasets using the secrets. 

The pipeline keeps the `download_latest_datasets_on_ready_for_review.yml` workflow - renamed `direct_download_urls_test_for_sources.yml` - as a test before accepting source contributions. A source `direct_download_url` must be working before the PR is merged in main, so that our cronjob will be able to harvest the latest dataset for this new source. 

Changes:

- `store_latest_dataset_on_approval.yml` is deleted
-  `download_latest_datasets_on_ready_for_review.yml` is renamed `direct_download_urls_test_for_sources.yml` and slightly modified so that it considers only the `direct_download_url`.

**Expected behavior:** 

The `latest_url` for a source won't be working until the next successful run of our daily cronjob.
The `direct_download_urls_test_for_sources.yml` workflow is executed for each commit of a PR containing "[SOURCES]" in its title.

Please make sure these boxes are checked before submitting your pull request - thanks!

- [x] Run the unit tests with `pytest` to make sure you didn't break anything
- [x] Format the title like "<short description of fix and changes>" (for example - "Check for null value before using field")
- [x] Linked all relevant issues
- [ ] ~Include screenshot(s) showing how this pull request works and fixes the issue(s)~

### CODE REVIEW

**Comment by emmambd** [comment]
`The latest_url for a source won't be working until the next successful run of our daily cronjob.` Can you clarify that this means the latest_url for a source won't be _up-to-date_ with the new URL? This **does not** break the latest URL, correct? @maximearmstrong

**Comment by maximearmstrong** [comment]
@emmambd No, it means that the `latest_url` for the source will be broken (empty) until the first successful cronjob as the dataset won't be stored until then.

**Comment by emmambd** [comment]
@maximearmstrong Will this also occur in instances where the URL is replaced? So for example, a `transitfeeds.com` URL is used, then it's replaced with the provider's URL. Would the latest dataset URL be broken or would it just store the transitfeeds.com URL's dataset until the cronjob runs?

**Comment by maximearmstrong** [comment]
@emmambd In this specific case, the URL won't be broken. It will be updated with the cronjob, but the previous version will still be accessible until the cronjob execution.

With the previous workflow (on approval), we made sure that at least one dataset was stored for a source and that the `latest_url` was working fine. Now, only the cronjob will be in charge in storing and doing that verification. The daily report will let us know if something went wrong and we'll be able to re-run the jobs or fix the problem if needed.

**Comment by emmambd** [comment]
@maximearmstrong This makes sense to me - thanks for clarifying!

**Review by emmambd — APPROVED** [review]

**Pull request merged**
