### PR TITLE
feat: add welcome messages

### PR DESCRIPTION
**Pull request by emmambd**
Adding a welcome bot for new PRs, merging PRs, and new issues.

### CODE REVIEW

**Comment by emmambd** [comment]
@maximearmstrong I've taken @isabelle-dr's excellent work on the welcome bot for the GTFS Schedule Validator repo and modified it slightly for the catalogs. Please test doing the following on [my fork](https://github.com/emmambd/mobility-database-catalogs): 

- Create an issue
- Create a PR

**Comment by isabelle-dr** [comment]
I opened a PR and couldn't open an issue, you'll need to tick the box in "Settings" here:
Screen Shot 2022-08-29 at 5 13 45 PM

The welcome bot didn't send its message, did you Install the bot on your forked repo? 
Ref: the instructions here https://github.com/apps/welcome

**Comment by emmambd** [comment]
@isabelle-dr Thanks for testing! I've updated the settings and app configuration now.

**Comment by isabelle-dr** [comment]
No problem, let me know if you'd like me to test something else. 
The PR flow will have to be tested by someone else since I already opened one. 

giphy

**Comment by emmambd** [comment]
@maximearmstrong It looks like issue and PR merge messages work, so if you can test opening a new PR we should be ready to merge!

**Review by maximearmstrong — APPROVED** [review]
This is great! Thanks @emmambd

**Pull request merged**
