### PR TITLE
fix: Update unknown names [SOURCES]

### PR DESCRIPTION
**Pull request by sethherr**
Correct filenames: 

- `catalogs/sources/gtfs/realtime/unknown-unknown-sonoma-marin-area-rail-transit-smart-gtfs-rt-vp-1576.json`
- `catalogs/sources/gtfs/realtime/unknown-unknown-sonoma-marin-area-rail-transit-smart-gtfs-rt-tu-1577.json`
 - `catalogs/sources/gtfs/realtime/unknown-unknown-central-florida-regional-transit-authority-lynx-gtfs-rt-sa-1768.json`
 - `catalogs/sources/gtfs/realtime/unknown-unknown-city-of-seattle-streetcar-gtfs-rt-sa-1547.json`
 - `catalogs/sources/gtfs/realtime/unknown-unknown-city-of-seattle-streetcar-gtfs-rt-tu-1548.json`
 - `catalogs/sources/gtfs/realtime/unknown-unknown-city-of-seattle-streetcar-gtfs-rt-vp-1546.json`
 - `catalogs/sources/gtfs/realtime/unknown-unknown-durham-region-transit-gtfs-rt-sa-1467.json`
 - `catalogs/sources/gtfs/realtime/unknown-unknown-durham-region-transit-gtfs-rt-tu-1468.json`
 - `catalogs/sources/gtfs/realtime/unknown-unknown-durham-region-transit-gtfs-rt-vp-1466.json`
 - `catalogs/sources/gtfs/realtime/unknown-unknown-ilevia-metropole-europeenne-de-lille-gtfs-rt-t-u-1792.json`
 - `catalogs/sources/gtfs/realtime/unknown-unknown-la-metro-gtfs-rt-tu-1575.json`
 - `catalogs/sources/gtfs/realtime/unknown-unknown-la-metro-gtfs-rt-vp-1574.json`
 - `catalogs/sources/gtfs/realtime/unknown-unknown-staten-island-railway-gtfs-rt-vp-tu-1637.json`
 - `catalogs/sources/gtfs/realtime/unknown-unknown-thousand-oaks-transit-gtfs-rt-sa-1689.json`

### CODE REVIEW

**Comment by emmambd** [comment]
Hi @sethherr ! The location data for GTFS Realtime feeds is generated based on the `static_reference` GTFS Schedule feed. Do you know which GTFS Schedule feeds match these realtime feeds? If so, you can add that to this PR as well and we can change the realtime feed names.

**Comment by sethherr** [comment]
@emmambd the matching GTFS feeds were _not_ miss-named, just these GTFS-RT feeds.

I added the `static_reference` for 1466, 1467, 1468, 1574, 1575, 1576, 1577, 1689, and 1768

I couldn't find a matching GTFS feed for the Seattle Streetcar (1546, 1547, 1548).

I couldn't find a matching GTFS feed for State Island Railway (1637)

It doesn't seem like [1792](https://github.com/MobilityData/mobility-database-catalogs/blob/main/catalogs/sources/gtfs/realtime/unknown-unknown-ilevia-metropole-europeenne-de-lille-gtfs-rt-t-u-1792.json) has a matching feed either ([1201](https://github.com/MobilityData/mobility-database-catalogs/blob/a6080b2520766ec58fd713bf53a76cf1f55810bf/catalogs/sources/gtfs/schedule/fr-hauts-de-france-reseau-de-transport-transpole-de-la-metropole-europeenne-de-lille-gtfs-1201.json) is close, but not the same).

**Comment by emmambd** [comment]
@sethherr This is awesome! Is 267 not the matching GTFS feed for Seattle Streetcar? If not, I can ask about it.

516 looks like the right feed for Staten Island Railway. I also found that 1201 was out of date – it should match 1792 now.

**Comment by sethherr** [comment]
It really doesn't seem like 267 is Seattle streetcar, Yakima is not Seattle. I found [this website](https://www.soundtransit.org/help-contacts/business-information/open-transit-data-otd), but couldn't find the actual GTFS data.

> 516 looks like the right feed for Staten Island Railway.

That seems correct - but that seems like it means that it (1637) should be deleted, and the name property of [1635](https://github.com/MobilityData/mobility-database-catalogs/blob/6d51dafb9a9896c72119e484488e90119b9c5e0a/catalogs/sources/gtfs/realtime/us-new-york-nyc-subway-1-gtfs-rt-vp-tu-1635.json#L9) should be updated to include Staten Island Railway. I've done that now.

1201 does match now, I updated it.

**Comment by emmambd** [comment]
@sethherr My mistake - based on the agency ids here https://www.soundtransit.org/help-contacts/business-information/open-transit-data-otd/otd-downloads it looks like 1080 is the match for Seattle Streetcar. 

Based on https://api.mta.info/#/subwayRealTimeFeeds, it doesn't look like Staten Island Railway realtime is provided in 1637. It looks like both 1637 and 1635 point to 516. 

Thank you for doing this cleanup!

**Comment by sethherr** [comment]
> Based on https://api.mta.info/#/subwayRealTimeFeeds, it doesn't look like Staten Island Railway realtime is provided in 1637. It looks like both 1637 and 1635 point to 516.

@emmambd are you saying that 1635 shouldn’t be updated to include “and Staten Island Railway”? 1637 has exactly the same information as 1635, so it doesn’t seem like it should be a separate record to me, which is why I deleted it.

**Comment by emmambd** [comment]
@sethherr After opening both, it doesn't look like the same realtime data. Right now, for example, in https://api-endpoint.mta.info/Dataservice/mtagtfsfeeds/nyct%2Fgtfs, I see 

> trip {
      trip_id: "091400_1..S03R"
      route_id: "1"
      start_date: "20230724"
    }
    stop_time_update {
      stop_id: "142S"
      arrival {
        time: 1690229325
      }
}

The trip_id matches a trip_id for the 1 Line. 

When I open https://api-endpoint.mta.info/Dataservice/mtagtfsfeeds/nyct%2Fgtfs-si, I see 

> trip {
  trip_id: "093600_SI..S"
  route_id: "SI"
  start_time: "15:36:00"
  start_date: "20230724"
}
stop_time_update {
  stop_id: "S13S"
  arrival {
    time: 1690229595
  }
  departure {
    time: 1690229595
  }
}

The trip_id matches a trip_id for the Staten Island Railway route. 

It looks like there are 2 realtime feeds that point to the same GTFS Schedule feed that's aggregated all routes together, but https://api-endpoint.mta.info/Dataservice/mtagtfsfeeds/nyct%2Fgtfs-si is for Staten Island realtime updates. [This matches the Subway Feeds list MTA shares on their developer portal](https://api.mta.info/#/subwayRealTimeFeeds).

**Comment by sethherr** [comment]
Wow, sorry for not looking closely enough - those are indeed different URLs. I've added 1637 back in with a statuc_reference of 516.

**Review by emmambd — APPROVED** [review]
Thanks so much @sethherr! This is an awesome clean-up effort.

**Pull request merged**
