### PR TITLE
Update us-california-fresno-county-rural-transit-agency-fcrta-gtfs-85.json [SOURCES]

### PR DESCRIPTION
**Pull request by walkerconsultants**
Updating to current GTFS feed: https://rapid.nationalrtap.org/GTFSFileManagement/UserUploadFiles/7869/google_transit.zip

Hosted on FCRTA's Website: https://www.ruraltransit.org/transportation-guide/park-and-ride-2

[google_transit.zip](https://github.com/MobilityData/mobility-database-catalogs/files/9263826/google_transit.zip)
/

### CODE REVIEW

**Comment by emmambd** [comment]
Thank you for this update and your first contribution, @walkerconsultants! This is great. Could you change the status to `active` so that the new URL is clearly usable? Once that is complete, we can merge.

**Comment by walkerconsultants** [comment]
Thanks Emma, I believe I changed the status to active, would you mind double checking? Thanks!

Joyfully,

Christian Turner (he/him)
Consultant
***@***.***
707 Wilshire Blvd, Suite 3650 |  Los Angeles, CA 90017
D  213.248.1951  |  O  213.488.4911
walkerconsultants.com<https://walkerconsultants.com/service/planning-mobility/> | Blog<http://walkerconsultants.com/news/> | Facebook<https://www.facebook.com/ask.us.WalkerConsultants/>| LinkedIn<https://www.linkedin.com/company/24929/> | Twitter<https://twitter.com/walkerconslts/>

**Comment by emmambd** [comment]
Hi Christian @walkerconsultants - [looking at the file changes](https://github.com/MobilityData/mobility-database-catalogs/pull/202/files), it looks like the URL was changed successfully but the status is still `inactive`. Let me know if you need any help with this. You should be able to change it by using the update operation - `update_gtfs_schedule_source(mdb_source_id=85, status="active")`

**Review by walkerconsultants — COMMENTED** [review]
changing status to 'active'

**Review by maximearmstrong — APPROVED** [review]
LGTM! Thanks @walkerconsultants

**Pull request merged**
